version: "3.9"
services:
  serverless-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src:/opt/app/pa-media/api/src
  docs:
    image: swaggerapi/swagger-ui
    ports:
      - "3001:8080"
    volumes:
      - ./docs:/usr/share/nginx/html/docs
      - ./coverage/lcov-report:/usr/share/nginx/html/coverage
    environment:
      - SWAGGER_JSON_URL=/docs/openapi.json
  redis:
    image: redis
    ports:
     - "6379:6379"
