service: pa-media-technical-challenge

frameworkVersion: '2'

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    shouldStartNameWithService: true

functions:
  get-lists:
    handler: src/get-lists/index.main
    events:
      - http:
          path: /v1/list
          method: get
  create-list:
    handler: src/create-list/index.main
    events:
      - http:
          path: /v1/list/{listKey}
          method: put
          request:
            parameters:
              paths:
                listKey: true
  remove-list:
    handler: src/remove-list/index.main
    events:
      - http:
          path: /v1/list/{listKey}
          method: delete
          request:
            parameters:
              paths:
                listKey: true
  create-item:
    handler: src/create-item/index.main
    events:
      - http:
          path: /v1/list/{listKey}/item/{itemKey}
          method: put
          request:
            parameters:
              paths:
                listKey: true
                itemKey: true
custom:
  serverless-offline:
    host: 0.0.0.0
