jobs:
  test:
    docker:
      - image: circleci/node:12.20.0
    steps:
      - checkout
      - run: npm ci
      - run: npm t
      - store_artifacts:
          path: test-results
workflows:
  version: 2
  main:
    jobs:
      - test
